* ruby on rails
** create
*** rails new sample_app --skip-test-unit
*** cd sample_app
*** rails generate controller StaticPages home help --no-test-framework
** bundle
*** bundle install --without production (except Gemfile items like: group :production do gem 'pg', '0.15.1' end)
*** bundle update
*** bundle install (the exception of production items auto keep)
** rails & rake cmd(do & redo operator)
*** rails generate controller FooBars baz quux & rails destroy controller FooBars baz quux
*** rails generate model Foo bar:string baz:integer & rails destroy model Foo
*** rake db:migrate & rake db:rollback & rake db:migrate VERSION=0(VERSION is genrated by migrate, echo migrate will cause VERSION++)
** test
*** add items in Gemfile (group :development, :test do gem 'rspec-rails', '~> 3.6' end)
*** bundle install
*** rails generate rspec:install
*** rails generate integration_test static_pages
*** bundle exec rspec
*** Guard for auto test (https://github.com/guard/guard)
*** Spork speed up test (add item for rails version>4: gem 'spork-rails', github: 'railstutorial/spork-rails')
* docker
curl https://registry.hub.docker.com//v1/repositories/ubuntu/tags | python -mjson.tool

docker run -i -t ubuntu:14.04 /bin/bash

docker exec -it tender_shockley bash

docker -dD

docker rmi -f $(docker images -q -a -f dangling=true)


sed -i "s%localhost%10.200.78.238%" cmd/registry/config.yml
curl -v -X GET http://localhost:5000/v2/hello-mine/tags/list

git clone git@cdpzit.com:~/project.git gitgit
2.6 打包镜像
docker save debian02 >/root/debian02.tar   #debian02镜像打包

2.7 在另外的机器上导入镜像
docker load < debian02.tar   #导入镜像
docker images   #查看存在的镜像

➜  ~  docker-machine env default
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="/Users/f0x/.docker/machine/machines/default"
export DOCKER_MACHINE_NAME="default"

* hosts
** https://raw.githubusercontent.com/lennylxx/ipv6-hosts/master/hosts
* bash tech:
** array
If you're used to a "standard" *NIX shell you may not be familiar with bash's array feature. Although not as powerful as similar constructs in the P languages (Perl, Python, and PHP) and others, they are often quite useful.

Bash arrays have numbered indexes only, but they are sparse, ie you don't have to define all the indexes. An entire array can be assigned by enclosing the array items in parenthesis:

  arr=(Hello World)
Individual items can be assigned with the familiar array syntax (unless you're used to Basic or Fortran):
  arr[0]=Hello
  arr[1]=World
But it gets a bit ugly when you want to refer to an array item:
  echo ${arr[0]} ${arr[1]}
To quote from the man page:
The braces are required to avoid conflicts with pathname expansion.
In addition the following funky constructs are available:

  ${arr[*]}         # All of the items in the array
  ${!arr[*]}        # All of the indexes in the array
  ${#arr[*]}        # Number of items in the array
  ${#arr[0]}        # Length of item zero
The ${!arr[*]} is a relatively new addition to bash, it was not part of the original array implementation.
The following example shows some simple array usage (note the "[index]=value" assignment to assign a specific index):

#!/bin/bash

array=(one two three four [5]=five)

echo "Array size: ${#array[*]}"

echo "Array items:"
for item in ${array[*]}
do
    printf "   %s\n" $item
done

echo "Array indexes:"
for index in ${!array[*]}
do
    printf "   %d\n" $index
done

echo "Array items and indexes:"
for index in ${!array[*]}
do
    printf "%4d: %s\n" $index ${array[$index]}
done
Running it produces the following output:
Array size: 5
Array items:
   one
   two
   three
   four
   five
Array indexes:
   0
   1
   2
   3
   5
Array items and indexes:
   0: one
   1: two
   2: three
   3: four
   5: five
Note that the "@" sign can be used instead of the "*" in constructs such as ${arr[*]}, the result is the same except when expanding to the items of the array within a quoted string. In this case the behavior is the same as when expanding "$*" and "$@" within quoted strings: "${arr[*]}" returns all the items as a single word, whereas "${arr[@]}" returns each item as a separate word.

The following example shows how unquoted, quoted "*", and quoted "@" affect the expansion (particularly important when the array items themselves contain spaces):

#!/bin/bash

array=("first item" "second item" "third" "item")

echo "Number of items in original array: ${#array[*]}"
for ix in ${!array[*]}
do
    printf "   %s\n" "${array[$ix]}"
done
echo

arr=(${array[*]})
echo "After unquoted expansion: ${#arr[*]}"
for ix in ${!arr[*]}
do
    printf "   %s\n" "${arr[$ix]}"
done
echo

arr=("${array[*]}")
echo "After * quoted expansion: ${#arr[*]}"
for ix in ${!arr[*]}
do
    printf "   %s\n" "${arr[$ix]}"
done
echo

arr=("${array[@]}")
echo "After @ quoted expansion: ${#arr[*]}"
for ix in ${!arr[*]}
do
    printf "   %s\n" "${arr[$ix]}"
done
When run it outputs:
Number of items in original array: 4
   first item
   second item
   third
   item

After unquoted expansion: 6
   first
   item
   second
   item
   third
   item

After * quoted expansion: 1
   first item second item third item

After @ quoted expansion: 4
   first item
   second item
   third
   item
* ftp tech
wget ftp://username:password@SERVERNAME/directory/file
wget ftp://share:share@10.220.128.5/Crono\ Team/Lin\ Wang/book/*
* ubuntu 15.10 set text mode
To boot Ubuntu 16.04 Desktop without X one time, add systemd.unit=multi-user.target to the linux command line in GRUB.

To make this the default, use
sudo systemctl set-default multi-user.target

To return to default booting into X, use
sudo systemctl set-default graphical.target

To see the current default target,
sudo systemctl get-default

* debug:
** perl -d myscript.pl b /opt/NBUAppliance/scripts/nbu_runcmd.pm:112 a pprint "\n===============================\n";print $cmd;print "\n*******************************\n";print $stdout B*
** python -m pdb myscript.py
* spacemacs
** change line num format search "linum-format"
* getting the hex codes(iterm2)
** xxd -psd & just input key
