* 简历:
*** 自我评价
**** chinese
认真务实,踏实进取,乐于助人,有团队精神,有丰富的工作经验和独立思考独立解决问题的能力,表达沟通能力不错,热爱并喜欢钻研各种技术工具以提高工作效率,不断深入了解计算机,编程是兴趣,个人兴趣还包括阅读,足球,旅游等
**** english
Pragmatic and enterprising, willing to share experience with others, have team spirit, have rich work experience and independent thinking ability to solve problem, good at communication, love and growing understanding of computer, get a lot of fun in the programming
*** 项目经验
**** chinese
索贝数码  2007.11 – 2014.6
  Fics 集群系统
  运行环境：linux win 7/8
  开发工具：zookeeper,gdb,emaces…
  项目描述：小规模,高性能,可扩展的集群文件系统
  责任描述：负责集群系统中对象存储层的设计和开发,数据一致性,容灾,冗余,扩展,整理.

  Fishare 分布式文件系统(san文件系统) 
  运行环境： win XP/2003/7 
  开发工具： ddk,windbg,softice,vmware,vs2008… 
  项目描述：分布式文件系统,主要用于替代stornext组建基于局域网的存储共享系统. 
  责任描述：主要负责其中磁盘层的驱动开发,提供多磁盘管理,多磁盘合并为单卷,磁盘异常处理,磁盘流量控制,提供磁盘测试脚本,磁盘缓存,磁盘独占,磁盘网络接口,磁盘映射工具,磁盘守护服务,磁盘层api等 . 

  流媒体大缓存 
  运行环境：win XP/2003/7 
  开发工具：pc,vs2008… 
  项目描述：支持小数据块大任务并发时网络和磁盘带宽的极限利用(如1000路128kb读写数据) 
  责任描述：负责此缓存模块的独立开发 
**** english
  Sobey		2007.11 – 2014.6
 
  Fics cluster storage system（2010.11 – 2014.6）
  environment：linux win 7/8
  develop tools：zookeeper,gdb,emaces,etc…
  project description：Small-scale, high-performance, scalable cluster file system
  project description：Responsible for object storage layer in cluster system ,design and development:data consistency, recovery,redundancy,expansion,etc. 

  Fishare SAN File system（2008.03 - 2010.11）
  environment：win XP/2003/7
  develop tools：ddk,windbg,softice,vmware,vs2008,etc…
  project description：Distributed file system, mainly used to replace stornext, to set up a LAN-based storage sharing system.
  project description： Primarily responsible to develop virtual driver disk layer, providing multi-disk management, virtual volume, disk exception processing, disk traffic control, test scripts, cache, disk-exclusive, disk network interfaces, disk mapping tool, disk guard services, etc.
 
  Streaming large cache
  environment：win XP/2003/7
  develop tools：vs2008,etc…
  project description：maximize disk bandwidth
  project description： Independent developers responsible for this cache module.

*** 专利

* org table: 
|   15 |   |   |   |   |
|   45 |   |   |   |   |
|   27 |   |   |   |   |
|   68 |   |   |   |   |
|  122 |   |   |   |   |
|   10 |   |   |   |   |
|   14 |   |   |   |   |
|   33 |   |   |   |   |
|   10 |   |   |   |   |
|   10 |   |   |   |   |
|   62 |   |   |   |   |
|   19 |   |   |   |   |
|   29 |   |   |   |   |
|   29 |   |   |   |   |
|   27 |   |   |   |   |
|   45 |   |   |   |   |
|  105 |   |   |   |   |
|  111 |   |   |   |   |
|  222 |   |   |   |   |
|    7 |   |   |   |   |
|  106 |   |   |   |   |
|------+---+---+---+---|
| 1116 | 0 | 0 | 0 | 0 |
#+TBLFM: @22=@1+@2
#+TBLFM: @22$1='(+ @1$1..@21$1);N

| test | xxx | ttt |
|------+-----+-----|
|      |     |     |
|------+-----+-----|



#+PLOT: title:"Citas" ind:1 deps:(3) type:2d with:histograms set:"yrange [0:]" file:"./plot.png"
| Sede      | Max cites | H-index |
| Chile     |    257.72 |   21.39 |
| Leeds     |    165.77 |   19.68 |
| Sao Paolo |     71.00 |   11.50 |
| Stockholm |    134.19 |   14.33 |
| Morelia   |    257.56 |   17.67 |

#+BEGIN_SRC python
  print "test\n";
#+END_SRC

| 吃饭 |  过路费 | 油钱 |   total |      evan | f0x&rabbit |
|   96 | 1116.75 |  200 |         |           |            |
|   29 |         |  255 |         |           |            |
|   73 |         |  280 |         |           |            |
|   93 |         |  140 |         |           |            |
|   71 |         |  292 |         |           |            |
|   59 |         |  245 |         |           |            |
|  124 |         |  140 |         |           |            |
|  111 |         |  235 |         |           |            |
|      |         |  270 |         |           |            |
|      |         |  220 |         |           |            |
|------+---------+------+---------+-----------+------------|
|  656 | 1116.75 | 2277 | 4049.75 | 1349.9167 |  7018.4933 |
#+TBLFM: @12='(+ @2..@11);N
#+TBLFM: @12$4='(+ @12$1..@12$3);N
#+TBLFM: @12$5=@12$4/3;N
#+TBLFM: @12$6=@12$4*2/3+1318.66+2000+1000;N

