### sample GET
GET https://example.com/topics/1 HTTP/1.1

### sample POST
POST https://example.com/comments HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

### getPushInfo POST
POST http://120.79.56.16/api/getPushInfo
content-type: application/json

{
  "pushInfo":[{"科室":"检验科","项目":"肝功能","指标":"总胆红素","异常值":"异常高"}]
}

### install iso ### 
GET http://10.220.142.150/cgi-bin/xgeo/configiso.pl?site=CD-B5214&model=5220&hosttype=HARDWARE&hostname=i27-eng138&isotype=2.6.1.1&iso=NB-2.6.1.1-20150219.iso&email=lin.wang1@veritas.com
###
GET http://10.220.142.150/cgi-bin/xgeo/configiso.pl?site=CD-B5214&model=5220&hosttype=HARDWARE&hostname=i127-eng138&isotype=2.7.2&iso=nba-2.7.2-6776520160413043311.iso&email=lin.wang1@veritas.com
### start installation ### 
GET http://10.220.142.150/cgi-bin/xgeo/bootpxe.pl?site=CD-B5214&ipmihost=10.220.138.128&hosttype=HARDWARE&user=sysadmin&pass=P@ssw0rd&robot=1

### install iso ### 
GET http://10.220.142.150/cgi-bin/xgeo/configiso.pl?site=CD-B5214&model=5220&hosttype=HARDWARE&hostname=i129-eng138&isotype=2.6.1.1&iso=NB-2.6.1.1-20150219.iso&email=lin.wang1@veritas.com
### start installation ### 
GET http://10.220.142.150/cgi-bin/xgeo/bootpxe.pl?site=CD-B5214&ipmihost=10.220.138.130&hosttype=HARDWARE&user=sysadmin&pass=P@ssw0rd&robot=1

### list iso version ###
GET http://10.220.142.150/cgi-bin/xgeo/listiso.pl?version=2.6.1.1&site=CD-B5214
###
GET http://10.220.142.150/cgi-bin/xgeo/listiso.pl?version=2.7.2&site=CD-B5214

###

GET http://115.28.40.27:8080/erp-0.1/api/store/moneyadds/2/2017-03-01/2017-03-31

###

GET http://115.28.40.27:8080/erp-0.1/api/store/refunds/2/2017-03-01/2017-03-31

###

GET http://115.28.40.27:8080/erp-test/api/sales/performance?storeId=2&fromDate=2017-03-01&toDate=2017-03-31

###

GET http://115.28.40.27:8080/erp-test/api/user/therapists/2/

###

GET http://115.28.40.27:8080/erp-0.1/api/transaction/consumptions/14/15/2017-03-01/2017-03-30

###

GET http://115.28.40.27:8080/erp-0.1/api/transaction/prjOrders/14/15/2017-03-01/2017-03-16

###

GET http://115.28.40.27:8080/erp-test/api/user/therapists/14

###

GET http://115.28.40.27:8080/erp-test/api/reserve/list?storeId=2&fromDate=2017-03-01&toDate=2017-04-30

###

POST http://115.28.40.27:8080/erp-test/api/reserve/sms?id=6

###

GET http://115.28.40.27:8080/erp-test/api/user/customers/120010

###

POST http://115.28.40.27:8080/erp-test/api/reserve/create
content-type: application/x-www-form-urlencoded

{
    "memberId": "6667011",
    "reserveTime": "2017-04-29 21:25",
    "reserveNotes": "111",
    "therapistId": "120228",
}

###

POST http://115.28.40.27:8080/erp-test/api/reserve/create?memberId=6667011&reserveTime=2017-04-29 21:25&reserveNotes=111&therapistId=120228

###

POST http://115.28.40.27:8080/erp-test/api/reserve/update
content-type: application/x-www-form-urlencoded

{
    "reserveId": "6",
    "therapistId": "120228",
}

###

GET http://115.28.40.27:8080/erp-test/api/user/authenticate/122222/123456

### bitbucket rest

POST https://stash.veritas.com/api/1.0/oauth/access_token
https://stash.veritas.com/projects/AS/repos/nba/pull-requests?create&targetBranch=refs%2Fheads%2Fmaster&sourceBranch=refs%2Fheads%2FAPPSOL-64792-2&targetRepoId=6001
https://stash.veritas.com/projects/AS/repos/nba/pull-requests?create&targetBranch=refs%2Fheads%2Fmaster&sourceBranch=refs%2Fheads%2Fb_nba_ws7&targetRepoId=6001
https://stash.veritas.com/projects/AS/repos/nba/pull-requests?create&targetBranch=refs%2Fheads%2Fmaster&sourceBranch=refs%2Fheads%2Fb_nba_ws7&targetRepoId=6001
https://stash.veritas.com/projects/AS/repos/nba/pull-requests?create&targetBranch=refs%2Fheads%2Fmaster&sourceBranch=refs%2Fheads%2Fb_nba_ws7&targetRepoId=6001

